### PR TITLE
Gracefully handle failed API groups from the discovery API

### LINKED ISSUE #1241: Backup completed with errors: [the server was unable to return a response in the time allotted
**What steps did you take and what happened:**
An ark schedule as below runs everyday.
Recently we observed that the scheduled backup is encountering errors.
NAME                STATUS    CREATED                         SCHEDULE     BACKUP TTL   LAST BACKUP   SELECTOR
ci-daily-backup     Enabled   2019-02-27 07:29:06 +0000 UTC   0 7 * * *    72h0m0s      1h ago        <none>
yaml-daily-backup   Enabled   2019-02-27 07:29:56 +0000 UTC   30 7 * * *   8760h0m0s    1h ago        <none>

The error message displayed is as below.

time="2019-02-27T07:51:52Z" level=info msg="Backup completed with errors: [the server was unable to return a response in the time allotted, but may still be processing the request (get serviceinstances.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get serviceplans.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get serviceclasses.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get clusterservicebrokers.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get servicebindings.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get clusterserviceclasses.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get servicebrokers.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get clusterserviceplans.servicecatalog.k8s.io)]" backup=heptio-ark/yaml-daily-backup-20190227073019 logSource="pkg/backup/backup.go:302"

**What did you expect to happen:**
The backup should be completed successfully.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/ark -n heptio-ark`
time="2019-02-27T07:51:53Z" level=error msg="backup failed" error="[the server was unable to return a response in the time allotted, but may still be processing the request (get serviceinstances.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get serviceplans.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get serviceclasses.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get clusterservicebrokers.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get servicebindings.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get clusterserviceclasses.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get servicebrokers.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get clusterserviceplans.servicecatalog.k8s.io)]" key=heptio-ark/yaml-daily-backup-20190227073019 logSource="pkg/controller/backup_controller.go:280"

* `ark backup describe <backupname>` or `kubectl get backup/<backupname> -n heptio-ark -o yaml`
Name:         yaml-daily-backup-20190227073019
Namespace:    heptio-ark
Labels:       ark-schedule=yaml-daily-backup
Annotations:  <none>

Phase:  Failed

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:

Snapshot PVs:  false

TTL:  8760h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2019-02-27 07:43:04 +0000 UTC
Completed:  2019-02-27 07:51:52 +0000 UTC

Expiration:  2020-02-27 07:43:04 +0000 UTC

Validation errors:  <none>

Persistent Volumes: <none included>

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This problem is occurring regularly on only 1 Kubernetes cluster.
When I run the backups manually after 2-3 hours, it completes successfully.

NAME                               STATUS      CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
ci-daily-backup-20190227110012     Completed   2019-02-27 07:20:12 +0000 UTC   2d                           <none>

**Environment:**

- Velero version (use `ark version`): 
# ark version
Version: v0.10.0
Git commit: v0.10.0
Git tree state: clean

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from `/etc/os-release`):
Amazon Linux

### LINKED ISSUE #1283: Gracefully handle failed API groups from the discovery API
**What steps did you take and what happened:**
After going through all the Azure steps in the documentation, velero fails to start with `An error occurred: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request`

**What did you expect to happen:**
Expected Velero to start

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

```
time="2019-03-13T20:13:32Z" level=info msg="setting log-level to INFO"
time="2019-03-13T20:13:32Z" level=info msg="Starting Velero server v0.11.0 (ab2fc65c02ecdcb9bb1690e3afe67a3b3196aebc)" logSource="pkg/cmd/server/server.go:134"
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/registry.go:98" name=pod
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/registry.go:98" name=pv
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/registry.go:98" name=serviceaccount
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=BlockStore logSource="pkg/plugin/registry.go:98" name=aws
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=BlockStore logSource="pkg/plugin/registry.go:98" name=azure
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=BlockStore logSource="pkg/plugin/registry.go:98" name=gcp
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/registry.go:98" name=aws
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/registry.go:98" name=azure
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/registry.go:98" name=gcp
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=job
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=pod
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=restic
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=service
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=serviceaccount
time="2019-03-13T20:13:32Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:322" namespace=velero
time="2019-03-13T20:13:32Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:328" namespace=velero
An error occurred: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request

```

**Environment:**

- Velero version (use `velero version`): 

```
Client:
	Version: v0.11.0
	Git commit: ab2fc65c02ecdcb9bb1690e3afe67a3b3196aebc
<error getting server version: timed out waiting for server status request to be processed>
```

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:47Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version:
AKS v1.11.5

- Cloud provider or hardware configuration:
Azure using AKS

### PR DESCRIPTION
**Pull request by fabito**
Fixes #1283 
Fixes #1241 

It improves discovery helper's error handling when `ErrGroupDiscoveryFailed` is returned by `discoveryClient.ServerPreferredResources()`. It now logs the details about the missing groups and continue the execution flow with the partial results.

I'd like to know how would you unit test this change. 

```go
type helper struct {
	discoveryClient discovery.DiscoveryInterface
	logger          logrus.FieldLogger

	// lock guards mapper, resources and resourcesMap
	lock         sync.RWMutex
	mapper       meta.RESTMapper
	resources    []*metav1.APIResourceList
	resourcesMap map[schema.GroupVersionResource]metav1.APIResource
	apiGroups    []metav1.APIGroup
}

Is it difficult to mock `discovery.DiscoveryInterface` and `meta.RESTMapper` ?
```

Signed-off-by: fabito <fuechi@ciandt.com>

### CODE REVIEW

**Comment by skriss** [comment]
Thanks for this @fabito!  Re: unit testing - I'm thinking we might want to do a couple of things to make this easier.  First - rather than having `NewHelper(...)` accept a `discovery.DiscoveryInterface`, define a new interface in this package, like the following:

```go
type DiscoveryInterface interface {
    ServerPreferredResources() ([]*metav1.APIResourceList, error)
    ServerGroups() (*metav1.APIGroupList, error)
}
```

Since these are the only two methods we actually use.  Then, we can create a fake/mock that implements this interface, and use it for testing.  You could implement a simple fake for `ServerPreferredResources` where you tell it ahead of time what to return.  

Second, it might be easiest to split the implementation of `Refresh` up into two helpers - the first can deal with the rest mapper, and the second can deal with getting the server resources (something like from https://github.com/heptio/velero/blob/a52ccd5db8bcd9412cb11b456765ba456a7e3db4/pkg/discovery/helper.go#L110 on).  Then - you can just unit test the second one and not have to worry about faking the rest mapper for now.

**Comment by fabito** [comment]
@skriss ,

The `shortcutExpander` also depends on `k8s.io/client-go/discovery`  (I think it only uses the `ServerResources` function) :

https://github.com/heptio/velero/blob/a52ccd5db8bcd9412cb11b456765ba456a7e3db4/pkg/discovery/helper.go#L104

Does it make sense to move the new `DiscoveryInterface` interface to `shortcut_expander.go`  in order to avoid circular dependency ?

**Comment by skriss** [comment]
Ah. So maybe keep the `NewHelper` function as-is, accepting a `DiscoveryInterface`, but then still define a new interface that the new helper method will accept?

File: pkg/discovery/helper.go [hunk 1]
```diff
@@ -109,7 +109,11 @@ func (h *helper) Refresh() error {
 
 	preferredResources, err := h.discoveryClient.ServerPreferredResources()
 	if err != nil {
-		return errors.WithStack(err)
+		if discovery.IsGroupDiscoveryFailedError(err) {
+			h.logger.Warnf("Failed to discover some groups: %v", err.(*discovery.ErrGroupDiscoveryFailed).Groups)
```
Comment (skriss) [inline pkg/discovery/helper.go]: I think it might be a little easier to read the log if instead of logging everything in one line, we loop through the groups:

```
for groupVersion, err := range err.(*discovery.ErrGroupDiscoveryFailed).Groups {
    // h.logger.WithError(err).Warnf(...)
}
```

**Comment by skriss** [comment]
@fabito let me know if you need any more input on this.  If the unit testing is tripping you up, I'm happy to help out!

File: pkg/discovery/helper.go [hunk 2]
```diff
@@ -109,7 +109,11 @@ func (h *helper) Refresh() error {
 
 	preferredResources, err := h.discoveryClient.ServerPreferredResources()
 	if err != nil {
-		return errors.WithStack(err)
+		if discovery.IsGroupDiscoveryFailedError(err) {
```
Comment (skriss) [inline pkg/discovery/helper.go]: this isn't a must-change, but since we end up type-asserting the error on the next line anyway, I'd probably instead do this:

```
if discoveryErr, ok := err.(*discovery.ErrGroupDiscoveryFailed); ok {
    // log failed groups, from discoveryErr.Groups
} else {
    return errors.WithStack(err)
}

**Comment by fabito** [comment]
> @fabito let me know if you need any more input on this. If the unit testing is tripping you up, I'm happy to help out!

Hi @skriss , thanks for your guidance. I think I got it. Now I will just make `NewFakeServerResourcesInterface` customizable and then add the test cases.

File: pkg/discovery/helper.go [hunk 3]
```diff
@@ -51,6 +51,12 @@ type Helper interface {
 	APIGroups() []metav1.APIGroup
 }
 
+// DiscoveryInterface exposes functions for Kubernetes discovery
```
Comment (skriss) [inline pkg/discovery/helper.go]: s/DiscoveryInterface/ServerResourcesInterface

Also, this interface doesn't need to be exported given how you're using it - so can be `type serverResourcesInterface interface`
