### PR TITLE
Fix restoring GCP regional disks

### LINKED ISSUE #1183: Restoring GCP Regional pv error
**Description**

Restore  for regional storage class on GCP fail with this error  : Invalid value for field 'resource.replicaZones[0]': ''. Exactly 2 replica zones must be set for regional disks 

Standard storage class restore is working.

**The output of the following commands will help us better understand what's going on**:

ark create restore test2 --from-backup full01-20190204180049 --include-namespaces chris-test 
Restore request "test2" submitted successfully.

ark describe restore test2
Name:         test2
Namespace:    heptio-ark
Labels:       <none>
Annotations:  <none>

Backup:  full01-20190204180049

Namespaces:
  Included:  chris-test
  Excluded:  <none>

Resources:
  Included:        persistentvolumes
  Excluded:        nodes, events, events.events.k8s.io, backups.ark.heptio.com, restores.ark.heptio.com
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Phase:  Completed

Validation errors:  <none>

Warnings:
  Ark:        <none>
  Cluster:    <none>
  Namespaces: <none>

Errors:
  Ark:        <none>
  Cluster:  error executing PVAction for /tmp/878522100/resources/persistentvolumes/cluster/pvc-0c5099ee-289f-11e9-bbb9-42010aa20034.json: rpc error: code = Unknown desc = googleapi: Error
400: Invalid value for field 'resource.replicaZones[0]': ''. Exactly 2 replica zones must be set for regional disks., invalid
  Namespaces: <none>

**Anything else you would like to add:**

kubectl get pv pvc-5d8cb4c0-28bf-11e9-bbb9-42010aa20034 --show-labels

NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                     STORAGECLASS   REASON    AGE       LABELS
pvc-5d8cb4c0-28bf-11e9-bbb9-42010aa20034   10Gi       RWO            Delete           Bound     chris-test/pvc-regional   regional                 56s       failure-domain.beta.kubernetes.io/region=northamerica-northeast1,failure-domain.beta.kubernetes.io/zone=northamerica-northeast1-a__northamerica-northeast1-b

**Environment:**
* Ark version (use `ark version`):   0.10.1
* Kubernetes version (use `kubectl version`): v1.10.7
* Kubernetes installer & version: "v1.10.11-gke.1"
* Cloud provider or hardware configuration: GKE

### PR DESCRIPTION
**Pull request by nrb**
To create a regional disk, the URLs for the zones in which the disk is
replicated must be provided to the GCP API.

Fixes #1183

Signed-off-by: Nolan Brubaker <brubakern@vmware.com>

### CODE REVIEW

File: pkg/cloudprovider/gcp/block_store.go [hunk 1]
```diff
@@ -142,10 +159,11 @@ func (b *blockStore) CreateVolumeFromSnapshot(snapshotID, volumeType, volumeAZ s
 	}
 
 	if isMultiZone(volumeAZ) {
-		volumeRegion, err := parseRegion(volumeAZ)
+		volumeRegion, err := parseZone(volumeAZ)
 		if err != nil {
 			return "", err
 		}
+		disk.ReplicaZones = createZoneURLs(b.project, volumeAZ)
```
Comment (skriss) [inline pkg/cloudprovider/gcp/block_store.go]: I think there may be an option to not hardcode the URL template -- you should be able to do something like:

```
zone, err := b.gce.Zones.Get("<project>", "zone>").Do()
// TODO handle error
url := zone.SelfLink
```

The `url` value looks like it will be a relative one, e.g. "/projects/<proj>/..." -- but I *think* based on other API documentation that this should be an acceptable value for `ReplicaZones`.  If this works, I think it's probably preferable.

Comment (nrb) [reply pkg/cloudprovider/gcp/block_store.go]: Cool, thanks. I think I'd prefer that to a templated URL, too. Will give it a test.

Comment (skriss) [reply pkg/cloudprovider/gcp/block_store.go]: Not 100% sure that the relative URL will be accepted, but 🤞

Comment (nrb) [reply pkg/cloudprovider/gcp/block_store.go]: It works!
 
```
% k get pv -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
    labels:
      failure-domain.beta.kubernetes.io/region: us-west1
      failure-domain.beta.kubernetes.io/zone: us-west1-b__us-west1-c
      velero-restore: nginx-regional-20190211133203
      velero.io/backup-name: nginx-regional
      velero.io/restore-name: nginx-regional-20190211133203
```

I'll look around how to make the unit testing work with this client call.

Comment (nrb) [reply pkg/cloudprovider/gcp/block_store.go]: Changed, though I didn't mock out the client seeing as none of the rest of that logic is mocked currently.

Comment (skriss) [reply pkg/cloudprovider/gcp/block_store.go]: Yeah, I think it's OK for now given precedent. Is this otherwise good to go? I'll do a quick test on it as well - got any sample YAMLs I could use?

File: pkg/cloudprovider/gcp/block_store.go [hunk 2]
```diff
@@ -100,19 +100,19 @@ func isMultiZone(volumeAZ string) bool {
...
-// such as us-central1 and us-west1 only the region matching the cluster is used
+// When a custom storage class spans multiple geographical zones,
+// such as us-central1 and us-west1 only the zone matching the cluster is used
 // in the failure-domain tag.
 // For example
 //     Cluster nodes in us-central1-c, us-central1-f
 //     Storage class zones us-central1-a, us-central1-f, us-east1-a, us-east1-d
 //     The failure-domain tag would be: us-central1-a__us-central1-f
-func parseRegion(volumeAZ string) (string, error) {
+func parseZone(volumeAZ string) (string, error) {
```
[the remark this answers is not in the document]
Comment (nrb) [reply pkg/cloudprovider/gcp/block_store.go]: I took it back to `parseRegion` - I had misunderstood it on reading, and thought it was getting a zone, not a region, but you're correct.

**Comment by nrb** [comment]
Fixes and docs pushed. Will squash if they look good.

File: pkg/cloudprovider/gcp/block_store.go [hunk 3]
```diff
@@ -122,6 +125,23 @@ func parseRegion(volumeAZ string) (string, error) {
...
+func (b *blockStore) getZoneURLs(volumeAZ string) ([]string, error) {
+	zones := strings.Split(volumeAZ, zoneSeparator)
+	var zoneURLs []string
+	for _, z := range zones {
+		zone, err := b.gce.Zones.Get(b.project, z).Do()
+		if err != nil {
+			return nil, errors.WithStack(err)
+		}
+
+		url := zone.SelfLink
```
Comment (skriss) [inline pkg/cloudprovider/gcp/block_store.go]: no need to declare `url` here

File: pkg/cloudprovider/gcp/block_store.go [hunk 4]
```diff
@@ -142,10 +162,20 @@ func (b *blockStore) CreateVolumeFromSnapshot(snapshotID, volumeType, volumeAZ s
 	}
 
 	if isMultiZone(volumeAZ) {
+		// Zone the volume is in
```
Comment (skriss) [inline pkg/cloudprovider/gcp/block_store.go]: either remove or s/Zone/Region

File: pkg/cloudprovider/gcp/block_store_test.go [hunk 5]
```diff
@@ -209,6 +209,7 @@ func TestRegionHelpers(t *testing.T) {
 				assert.Equal(t, test.expectedError.Error(), err.Error())
 			}
 			assert.Equal(t, test.expectedRegion, region)
+
```
Comment (skriss) [inline pkg/cloudprovider/gcp/block_store_test.go]: remove

**Comment by skriss** [comment]
retest looks good

File: pkg/cloudprovider/gcp/block_store.go [hunk 6]
```diff
@@ -142,10 +162,20 @@ func (b *blockStore) CreateVolumeFromSnapshot(snapshotID, volumeType, volumeAZ s
...
 		volumeRegion, err := parseRegion(volumeAZ)
 		if err != nil {
 			return "", err
 		}
+
+		// URLS for zones that the volume is replicated to within GCP
```
Comment (carlisia) [inline pkg/cloudprovider/gcp/block_store.go]: s/URLS/URLs since you are going to be changing things :)

File: pkg/cloudprovider/gcp/block_store.go (hunk 4 above)
Comment (nrb) [reply pkg/cloudprovider/gcp/block_store.go]: Removed.

File: pkg/cloudprovider/gcp/block_store.go (hunk 3 above)
Comment (nrb) [reply pkg/cloudprovider/gcp/block_store.go]: Removed, just using `zone.SelfLink`

File: pkg/cloudprovider/gcp/block_store_test.go (hunk 5 above)
Comment (nrb) [reply pkg/cloudprovider/gcp/block_store_test.go]: Removed

File: pkg/cloudprovider/gcp/block_store.go (hunk 6 above)
Comment (nrb) [reply pkg/cloudprovider/gcp/block_store.go]: Changed
